#!/bin/bash
# AUTO-GENERATED by CHP — uses atomic check runner
LAW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHP_BASE="$(cd "$LAW_DIR/../../../../" && pwd)"
source "$CHP_BASE/core/common.sh"
source "$CHP_BASE/core/check-runner.sh"
run_checks "no-api-keys" "${1:-pre-commit}"
exit $?
