#!/bin/bash
# Test law-mutate.sh functions

set -e  # Exit on test failures

source "$(dirname "$0")/../core/common.sh"
source "$(dirname "$0")/../core/law-builder.sh"
source "$(dirname "$0")/../core/law-mutate.sh"

echo "Testing law-mutate.sh functions..."

# Setup: Create a test law with all three files
TEST_LAW_DIR="$CHP_BASE/docs/chp/laws/test-mutate-law"
mkdir -p "$TEST_LAW_DIR"

# Create law.json with one check
cat > "$TEST_LAW_DIR/law.json" << 'EOF'
{
  "name": "test-mutate-law",
  "severity": "error",
  "hooks": ["pre-commit"],
  "enabled": true,
  "failures": 0,
  "tightening_level": 0,
  "checks": [
    {
      "id": "check-1",
      "type": "pattern",
      "config": {"pattern": "console\\.log"},
      "severity": "block",
      "message": "Do not use console.log"
    }
  ]
}
EOF

# Create verify.sh sourcing check-runner
cat > "$TEST_LAW_DIR/verify.sh" << 'VERIFYEOF'
#!/bin/bash
# Verification script for law: test-mutate-law

LAW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHP_BASE="$(cd "$LAW_DIR/../../../../" && pwd)"

source "$CHP_BASE/core/common.sh"
source "$CHP_BASE/core/check-runner.sh"

run_checks "test-mutate-law" "${1:-pre-commit}"
exit $?
VERIFYEOF

# Create guidance.md with Severity and Failures headers
cat > "$TEST_LAW_DIR/guidance.md" << 'EOF'
<!-- AUTO-GENERATED by CHP -->
# Law: test-mutate-law

**Severity:** error
**Created:** 2026-04-25T00:00:00Z
**Failures:** 0

## Purpose

Test law for mutate tests.

## Guidance

This is a test law.
EOF

# Test 1: mutate_field updates severity in law.json
echo "Test 1: mutate_field updates severity in law.json"
mutate_field "test-mutate-law" "severity" "warn"
severity=$(get_law_meta "test-mutate-law" "severity")
if [ "$severity" = "warn" ]; then
    echo "  PASS: severity updated to warn"
else
    echo "  FAIL: Expected severity=warn, got $severity"
    exit 1
fi

# Test 2: mutate_field syncs severity to guidance.md header
echo "Test 2: mutate_field syncs severity to guidance.md header"
guidance_severity=$(sed -n 's/^\*\*Severity:\*\* \(.*\)$/\1/p' "$TEST_LAW_DIR/guidance.md" | head -1)
if [ "$guidance_severity" = "warn" ]; then
    echo "  PASS: guidance.md severity synced to warn"
else
    echo "  FAIL: Expected guidance.md severity=warn, got $guidance_severity"
    exit 1
fi

# Test 3: mutate_field fails for non-existent law
echo "Test 3: mutate_field fails for non-existent law"
if ! mutate_field "non-existent-law" "severity" "error" 2>/dev/null; then
    echo "  PASS: non-existent law handled correctly"
else
    echo "  FAIL: mutate_field should fail for non-existent law"
    exit 1
fi

# Test 4: mutate_status disables law (enabled=false in law.json)
echo "Test 4: mutate_status disables law (enabled=false)"
mutate_status "test-mutate-law" "disabled"
enabled=$(get_law_meta "test-mutate-law" "enabled")
if [ "$enabled" = "false" ]; then
    echo "  PASS: law disabled, enabled=false"
else
    echo "  FAIL: Expected enabled=false, got $enabled"
    exit 1
fi

# Test 5: mutate_status enables law (enabled=true in law.json)
echo "Test 5: mutate_status enables law (enabled=true)"
mutate_status "test-mutate-law" "enabled"
enabled=$(get_law_meta "test-mutate-law" "enabled")
if [ "$enabled" = "true" ]; then
    echo "  PASS: law enabled, enabled=true"
else
    echo "  FAIL: Expected enabled=true, got $enabled"
    exit 1
fi

# Test 6: mutate_failure increments failures in law.json
echo "Test 6: mutate_failure increments failures in law.json"
failures_before=$(get_law_meta "test-mutate-law" "failures")
mutate_failure "test-mutate-law"
failures_after=$(get_law_meta "test-mutate-law" "failures")
expected=$((failures_before + 1))
if [ "$failures_after" = "$expected" ]; then
    echo "  PASS: failures incremented from $failures_before to $failures_after"
else
    echo "  FAIL: Expected failures=$expected, got $failures_after"
    exit 1
fi

# Test 7: mutate_failure syncs failures to guidance.md header
echo "Test 7: mutate_failure syncs failures to guidance.md header"
guidance_failures=$(sed -n 's/^\*\*Failures:\*\* \(.*\)$/\1/p' "$TEST_LAW_DIR/guidance.md" | head -1)
if [ "$guidance_failures" = "$failures_after" ]; then
    echo "  PASS: guidance.md failures synced to $guidance_failures"
else
    echo "  FAIL: Expected guidance.md failures=$failures_after, got $guidance_failures"
    exit 1
fi

# Test 8: mutate_failure appends violation entry to guidance.md
echo "Test 8: mutate_failure appends violation entry to guidance.md"
lines_before=$(wc -l < "$TEST_LAW_DIR/guidance.md")
mutate_failure "test-mutate-law"
lines_after=$(wc -l < "$TEST_LAW_DIR/guidance.md")
if [ "$lines_after" -gt "$lines_before" ]; then
    echo "  PASS: violation entry appended (lines: $lines_before -> $lines_after)"
else
    echo "  FAIL: Expected more lines after violation, before=$lines_before after=$lines_after"
    exit 1
fi

# Test 9: mutate_reset clears failures and tightening_level to 0
echo "Test 9: mutate_reset clears failures and tightening_level to 0"
mutate_reset "test-mutate-law"
failures=$(get_law_meta "test-mutate-law" "failures")
tightening=$(get_law_meta "test-mutate-law" "tightening_level")
if [ "$failures" = "0" ] && [ "$tightening" = "0" ]; then
    echo "  PASS: failures=0 and tightening_level=0 after reset"
else
    echo "  FAIL: Expected failures=0 and tightening_level=0, got failures=$failures tightening_level=$tightening"
    exit 1
fi

# Test 10: mutate_reset syncs failures=0 to guidance.md header
echo "Test 10: mutate_reset syncs failures=0 to guidance.md header"
guidance_failures=$(sed -n 's/^\*\*Failures:\*\* \(.*\)$/\1/p' "$TEST_LAW_DIR/guidance.md" | head -1)
if [ "$guidance_failures" = "0" ]; then
    echo "  PASS: guidance.md failures synced to 0"
else
    echo "  FAIL: Expected guidance.md failures=0, got $guidance_failures"
    exit 1
fi

# Test 11: mutate_checks add (count goes from 1 to 2)
echo "Test 11: mutate_checks add (count goes from 1 to 2)"
check_count_before=$(jq '.checks | length' "$TEST_LAW_DIR/law.json")
new_check='{"id":"check-2","type":"pattern","config":{"pattern":"TODO"},"severity":"warn","message":"No TODOs allowed"}'
mutate_checks "test-mutate-law" "add" "$new_check"
check_count_after=$(jq '.checks | length' "$TEST_LAW_DIR/law.json")
if [ "$check_count_after" = "2" ]; then
    echo "  PASS: check count went from $check_count_before to $check_count_after"
else
    echo "  FAIL: Expected check count=2, got $check_count_after"
    exit 1
fi

# Test 12: mutate_checks regenerates verify.sh (contains run_checks)
echo "Test 12: mutate_checks regenerates verify.sh (contains run_checks)"
if grep -q 'run_checks' "$TEST_LAW_DIR/verify.sh"; then
    echo "  PASS: verify.sh contains run_checks"
else
    echo "  FAIL: verify.sh does not contain run_checks"
    exit 1
fi

# Test 13: mutate_checks remove (count goes from 2 to 1)
echo "Test 13: mutate_checks remove (count goes from 2 to 1)"
remove_check='{"id":"check-2"}'
mutate_checks "test-mutate-law" "remove" "$remove_check"
check_count_after=$(jq '.checks | length' "$TEST_LAW_DIR/law.json")
if [ "$check_count_after" = "1" ]; then
    echo "  PASS: check count went back to 1"
else
    echo "  FAIL: Expected check count=1, got $check_count_after"
    exit 1
fi

# Test 14: validate_consistency passes for consistent law
echo "Test 14: validate_consistency passes for consistent law"
if validate_consistency "test-mutate-law" 2>/dev/null; then
    echo "  PASS: consistent law validates successfully"
else
    echo "  FAIL: validate_consistency should pass for consistent law"
    exit 1
fi

# Test 15: validate_consistency detects severity drift
echo "Test 15: validate_consistency detects severity drift"
# Manually break law.json severity to create drift
tmpfile=$(mktemp_chp "chp_test_drift_XXXXXX")
jq '.severity = "info"' "$TEST_LAW_DIR/law.json" > "$tmpfile" && mv "$tmpfile" "$TEST_LAW_DIR/law.json"
if ! validate_consistency "test-mutate-law" 2>/dev/null; then
    echo "  PASS: severity drift detected correctly"
else
    echo "  FAIL: validate_consistency should detect severity drift"
    exit 1
fi
# Restore severity to match guidance
tmpfile=$(mktemp_chp "chp_test_restore_XXXXXX")
jq '.severity = "warn"' "$TEST_LAW_DIR/law.json" > "$tmpfile" && mv "$tmpfile" "$TEST_LAW_DIR/law.json"

# Cleanup: remove test law directory
rm -rf "$TEST_LAW_DIR"

echo ""
echo "All tests passed!"
